Add CNPG repo in publish workflow before packaging the chart (#31)
Publishing the chart currently fails to build dependencies:

> Error: no repository definition for
https://cloudnative-pg.github.io/charts. Please add the missing repos
via 'helm repo add'

- add the CNPG repo before building the dependencies